# Generated by Django 4.1.9 on 2023-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAttributes',
            fields=[
                ('diseaseNID', models.IntegerField(primary_key=True, serialize=False)),
                ('diseaseid', models.CharField(max_length=255)),
                ('diseasename', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diseaseAttributes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
