# Generated by Django 5.0.9 on 2024-11-06 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogMessage",
        ),
    ]
